# #################################### #
# Configuration file for Hakoirimusume #
# #################################### #
# ${VAR_NAME} will be replaced with the value of the environment variable VAR_NAME.
# See docs/configuration.md for more information.

# For testing
os.environ.path: ${PATH}

# Flask server
server.port: 8080

# LINE Messaging API
line.bot:
  channel-token: ${LINE_CHANNEL_ACCESS_TOKEN}
  channel-secret: ${LINE_CHANNEL_SECRET}
  handler.path: /callback

# Imgur API 
imgur:
  client-id: ${IMGUR_CLIENT_ID}

# PiCamera & Sensor
hardware:
  camera-image: true  # If false, image area of Rabbit's House Report will be disappeared.
  bme280.i2c-bus: 1
  bme280.i2c-address: 0x76

# Hakoirimusume application
hakoirimusume:
  alert:
    condition:  # [!This value can be changed via LINE!]
      temperature: 26.5  # Â°C  float
      humidity: 60  # %  float
      pressure: null  # hPa  float
    interval: 3  # hour
    restrict:
      times-of-day: 5
      disable-message-threshold: 180  # messages / month
    action:
      type: null  # GET | POST | COMMAND | null
      # The following placeholders are available in 'target', 'header', 'body'.
      # {{IMAGE_URL}} : Imgur URL of image (will be replaced with empty string when camera image is not available)
      # {{TEMP}} : Current temperature (e.g., 25.0)
      # {{HUMID}} : Current humidity (e.g., 50.0)
      # {{PRESSURE}} : Current pressure (e.g., 1013.0)
      # {{DATE}} : yyyymmdd string of current date (e.g., 20240425)
      # {{TIME}} : HHMMSS string of current local time (e.g., 113911)
      target: null  # URL (type is GET or POST) | shell command (type is COMMAND) | null
      header: null  # String | null, ignored if type is not POST
      body: null  # String | null, ignored if type is not POST
      success-message: "å†·æˆ¿ã‚’ç‚¹ã‘ãŸã‚ˆï¼"  # String | null
      failure-message: "å†·æˆ¿ã‚’ç‚¹ã‘ã‚‹ã®ã«å¤±æ•—ã—ã¡ã‚ƒã£ãŸğŸ˜±\néƒ¨å±‹ã«æ¥ã¦ç‚¹ã‘ã¦ï¼ğŸ™"  # String | null
  # Aikotoba configs
  aikotoba:
    timeout: 60  # sec.
    sheeds: 
      - ["ãŠåˆ©å£ã§", "ã‹ã—ã“ãã¦", "è³¢ãã¦", "ã‹ã‚ã„ãã¦", "å¯æ„›ãã¦", "ã‚­ãƒ¥ãƒ¼ãƒˆã§", "ã’ã‚“ãã§", "å…ƒæ°—ã§", "äººè¦‹çŸ¥ã‚Šã§", "å„ªã—ãã¦"]
      - ["ã”æ©Ÿå«Œãª", "è‡ªç«‹ã—ãŸ", "ã‚ˆãé£Ÿã¹ã‚‹", "é£Ÿæ¬²æ—ºç››ãª", "å¤©æ‰ãª", "ãªã‚“ã§ã‚‚é£Ÿã¹ã‚‹ï¼Ÿ", "é•·å¯¿ãª", "é•·ç”Ÿããª", "ç”˜ãˆã‚“åŠãª", "ç™’ã•ã‚Œã‚‹"]
      - ["ã†ã•ã", "ã‚¦ã‚µã‚®", "Rabbit", "ãƒ©ãƒ“ãƒƒãƒˆ", "ã†ã•ã¡ã‚ƒã‚“", "ã†ã•ãã¡ã‚ƒã‚“", "ç®±å…¥ã‚Šå¨˜", "è€³ã®é•·ã„å®¶æ—", "ãƒ‰ãƒ¯ãƒ¼ãƒ•", "ãŠå§«ã•ã¾"]
  info.show-ip: true  # If true, show private IP address on the info command
  request.timeout: 300  # sec.
  remote-shutdown:
    enable: true
    available-authority-level: user  # user | admin
    command: "sudo shutdown -h -t 15"
    success-message: "15ç§’å¾Œã«ã‚·ãƒ£ãƒƒãƒˆãƒ€ã‚¦ãƒ³ã™ã‚‹ã­\nãŠã‚„ã™ã¿ãªã•ã„ğŸ˜´"
    failure-message: "ã‚·ãƒ£ãƒƒãƒˆãƒ€ã‚¦ãƒ³ã«å¤±æ•—ã—ã¡ã‚ƒã£ãŸğŸ˜±\nè¨­ç½®ã—ãŸäººã«ãã„ã¦ã¿ã¦ï¼ğŸ™"

# Generative filepaths
filepaths:
  database: "./hakoirimusume.db"
  sensor-data: "./sensor-data.csv"
  log-dir: ".logs"