# Hakoirimusume configuration file
# Relative path is available from Hakoirimusume root directory.

spring.application.name: Hakoirimusume

server:
  port : 8080

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:hakoirimusume.db
    username: hakoirimusume
    password: hm35712db7
  sql.init.mode: always
  jpa.database-platform: org.hibernate.community.dialect.SQLiteDialect
  jpa.open-in-view: false

line.bot:
  channel-token: ${LINE_CHANNEL_ACCESS_TOKEN}  # Put your Channel Access Token or ${env_val_name} to specify environment variable.
  channel-secret: ${LINE_CHANNEL_SECRET}  # Put your Channel Secret or ${env_val_name} to specify environment variable.
  handler.path: /callback  # LINE Messaging API Webhook URL will be "{Hakoirimusume server URL}{this value}".

hakoirimusume:
  richmenu:
    for-authorized-user: richmenu-926d8a458c54f8efbca72b268a485a46  # Rich menu ID for authorized user
  sensor-server:
    # Configure sensor component, see also: README.md
    endpoint: http://localhost/get # Endpoint for sensor data & camera image
    camera-endpoint : http://localhost/get?withcamera  # Endpoint for no camera image
  alert:
    to: [ # LINE user / group ID list to send alert
#      "Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
#      "Uyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
    ]
    polling-interval-sec: 300 # sec. >= 10
    condition:
      # current temperature or humidity >= {these value}  --->  send alert
      temperature: -1  # integer, float or -1 (no temperature condition)
      humidity: -1  # integer, float or -1 (no humidity condition)
    trigger-limit:
      interval: 3 # hours each
      daily-limit: -1 # times, if you'd like to specify -1, no limit will be applied.
    action:
      type: null  # "GET" | "POST" | "COMMAND" | null (no action will be executed)
      # The following placeholders are available in 'target', 'header', 'body'.
      # {{IMAGE_URL} : Imgur URL of image (will be replaced with empty string when camera image is not available)
      # {{TEMP}} : Current temperature (e.g., 25.0)
      # {{HUMID}} : Current humidity (e.g., 50.0)
      # {{PRESSURE}} : Current pressure (e.g., 1013.0)
      # {{DATE}} : yyyymmdd string of alert date (e.g., 20240425)
      # {{TIME}} : HHMMSS string of alert local time (e.g., 113911)
      target: "triggered-script.sh arg1 arg2"  # String, specify URL (when type is "GET" or "POST") or command (when type is "COMMAND")
      header: "POST Header" # null (no header) | String, contents of request header, valid only when type is "POST", this value will be ignored when type is not "POST"
      body: "POST Body"  # String, contents of request body, valid only when type is "POST", this value will be ignored when type is not "POST"
      success-message: "ã‚¨ã‚¢ã‚³ãƒ³ã‚’ç‚¹ã‘ãŸã‚ˆï¼"  # This string will be sent to users with alert on success executing action.
      failure-message: "å†·æˆ¿ã‚’ç‚¹ã‘ã‚‹ã®ã«å¤±æ•—ã—ã¡ã‚ƒã£ãŸğŸ˜±\néƒ¨å±‹ã«æ¥ã¦ç‚¹ã‘ã¦ã»ã—ã„ãªï¼ğŸ™"  # This string will be sent to users with alert on failure executing action.
  aikotoba:
    seeds: [ # aikotoba will be "{Random value of 1st list}{Random value of 2nd list}{Random value of 3rd list}..."
      ["ãŠåˆ©å£ã§", "ã‹ã—ã“ãã¦", "è³¢ãã¦", "ã‹ã‚ã„ãã¦", "å¯æ„›ãã¦", "ã‚­ãƒ¥ãƒ¼ãƒˆã§", "ã’ã‚“ãã§", "å…ƒæ°—ã§", "äººè¦‹çŸ¥ã‚Šã§", "å„ªã—ãã¦"],
      ["ã”æ©Ÿå«Œãª", "è‡ªç«‹ã—ãŸ", "ã‚ˆãé£Ÿã¹ã‚‹", "é£Ÿæ¬²æ—ºç››ãª", "å¤©æ‰ãª", "ãªã‚“ã§ã‚‚é£Ÿã¹ã‚‹ï¼Ÿ", "é•·å¯¿ãª", "é•·ç”Ÿããª", "ç”˜ãˆã‚“åŠãª", "ç™’ã•ã‚Œã‚‹"],
      ["ã†ã•ã", "ã‚¦ã‚µã‚®", "Rabbit", "ãƒ©ãƒ“ãƒƒãƒˆ", "ã†ã•ã¡ã‚ƒã‚“", "ã†ã•ãã¡ã‚ƒã‚“", "ç®±å…¥ã‚Šå¨˜", "è€³ã®é•·ã„å®¶æ—", "ãƒ‰ãƒ¯ãƒ¼ãƒ•", "ãŠå§«ã•ã¾"]
    ]
    timeout-sec: 60 # sec. After this value seconds, user need to regenerate new aikotoba.
  info.show-private-ip: true
  remote-shutdown:
    enable: true
    available-role: user  # user | admin
    command: "sudo shutdown -h -t 15"
    success-message: "15ç§’å¾Œã«ã‚·ãƒ£ãƒƒãƒˆãƒ€ã‚¦ãƒ³ã™ã‚‹ã­\nãŠã‚„ã™ã¿ãªã•ã„ğŸ˜´"
    failure-message: "ã‚·ãƒ£ãƒƒãƒˆãƒ€ã‚¦ãƒ³ã«å¤±æ•—ã—ã¡ã‚ƒã£ãŸğŸ˜±\nè¨­ç½®ã—ãŸäººã«ãã„ã¦ã¿ã¦ï¼ğŸ™"
  request.timeout-sec: 300  # sec.


# To remove Client wire logs. Please comment out following lines.
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
#
#logging.level:
#   com.linecorp.bot.client.wire: INFO